### ISSUE TITLE
Image zooms back to start position(ARNZoomImageTransition)

### ISSUE THREAD

**Issue by julianpomper** [xxxAIRINxxx/ARNTransitionAnimator#1]
When I select(present modal viewcontroller) a cell from my TableViewController which was not visible at the start of the Controller, and dismiss it(animate back the modal presented view controller) the image animates back to the coordinates where the cell was at the start of the Controller.

Can you help me?

**Comment by xxxAIRINxxx** [comment]
If that is your project-specific problem, i can not support.
If a bug in my code, i will be to support.

after that, 
If you are writing the code by reference to the ARNZoomImageTransition,
please write in there the issue.
