### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by carliskisantiago** [xxxAIRINxxx/ARNTransitionAnimator#8]
Hello,
I'm writing to know whether this framework will be available for Swift 3 or if you know a method to make it compatible.
Thanks in advance. 
Santiago.

**Comment by xxxAIRINxxx** [comment]
@carliskisantiago 
I working on creating a Swift 3 version.
but... Code varies greatly.

https://github.com/xxxAIRINxxx/ARNTransitionAnimator/tree/2.0.0

or, please make such a fork.

https://github.com/xxxAIRINxxx/ARNTransitionAnimator/pull/7
